Filmer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', include("contact.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include("main.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.MoviesView.as_view(), name='home'),
    path('filter/', views.FilterMoviesView.as_view(), name='filter'),
    path('search/', views.Search.as_view(), name='search'),
    path('add-rating/', views.AddStarRating.as_view(), name='add_rating'),
    path('<slug:slug>/', views.MovieDetailView.as_view(), name='movie_detail'),
    path('review/<int:pk>/', views.AddReview.as_view(), name='add_review'),
    path('actor/<str:slug>/', views.ActorView.as_view(), name='actor_detail'),
]

main/models.py
from django.db import models
from datetime import date
from django.urls import reverse


class Category(models.Model):
    """Категории"""
    name = models.CharField("Категории", max_length=150)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Actor(models.Model):
    """Актеры"""
    name = models.CharField("Имя", max_length=100)
    age = models.PositiveSmallIntegerField("Возраст", default=0)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="actors/")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("actor_detail", kwargs={'slug': self.name})

    class Meta:
        verbose_name = "Актеры и Режиссеры"
        verbose_name_plural = "Актеры и Режиссеры"


class Genre(models.Model):
    """Жанры"""
    name = models.CharField("Имя", max_length=100)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанры"
        verbose_name_plural = "Жанры"


class Movie(models.Model):
    """Фильмы"""
    title = models.CharField("Название", max_length=100)
    tagline = models.CharField("Слоган", max_length=100, default='')
    description = models.TextField("Описание")
    poster = models.ImageField("Постер", upload_to="movies/")
    year = models.PositiveSmallIntegerField("Дата выхода", default=2019)
    country = models.CharField("Страна", max_length=30)
    directors = models.ManyToManyField(Actor, verbose_name="режиссеры",
                                       related_name="film_director")
    actors = models.ManyToManyField(Actor, verbose_name="акстеры",
                                    related_name="film_actor")
    genres = models.ManyToManyField(Genre, verbose_name="жанры")
    world_premiere = models.DateField("Премьера в мире", default=date.today)
    budget = models.PositiveIntegerField("Бюджет", default=0, help_text="укажите сумму ы дорлларых")
    fees_in_usa = models.PositiveIntegerField("Сборы в США", default=0, help_text="укажите сумму ы дорлларых")
    fees_in_world = models.PositiveIntegerField("Сборы в мире", default=0, help_text="укажите сумму ы дорлларых")
    category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=160, unique=True)
    draft = models.BooleanField("Черновик", default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("movie_detail", kwargs={'slug': self.url})

    def get_review(self):
        return self.review_set.filter(parent__isnull=True)

    class Meta:
        verbose_name = "Фильмы"
        verbose_name_plural = "Фильмы"


class MovieShots(models.Model):
    """Кадры из фильма"""
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадры из фильма"
        verbose_name_plural = "Кадры из фильма"


class RatingStar(models.Model):
    """Звёзды рейтинга"""
    value = models.PositiveSmallIntegerField("Значение", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звёзды рейтинга"
        verbose_name_plural = "Звёзды рейтинга"
        ordering = ['-value']


class Rating(models.Model):
    """Рейтинг"""
    ip = models.CharField("IP адрес", max_length=15)
    stars = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="звёзды")
    movie = models.ForeignKey(Movie, on_delete=models.CharField, verbose_name="фильми")

    def __str__(self):
        return f"{self.stars} - {self.movie}"

    class Meta:
        verbose_name = "Рейтинги"
        verbose_name_plural = "Рейтинги"


class Review(models.Model):
    """Комментарий"""
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=50000)
    parent = models.ForeignKey("self", verbose_name="Родитель",
                               on_delete=models.SET_NULL, blank=True, null=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="фильм")

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Отзывы"
        verbose_name_plural = "Отзывы"

main/forms.py
from django import forms
from .models import Review, Rating, RatingStar


class ReviewForm(forms.ModelForm):
    """Форма добавления отзывов"""

    class Meta:
        model = Review
        fields = ('name', 'email', 'text')


class RatingForm(forms.ModelForm):
    """Форма добавления рейтинга"""
    stars = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ('stars',)

main/views.py
from django.shortcuts import redirect, HttpResponse
from django.views.generic.base import View
from django.views.generic import ListView, DetailView
from django.db.models import Q
from .models import Movie, Actor, Genre, Rating, RatingStar
from .forms import ReviewForm, RatingForm



class GenreYear:
    """Жанры и года выхода фильмов"""

    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        return Movie.objects.filter(draft=False).values('year')


class MoviesView(GenreYear, ListView):
    """Список фильмов"""
    model = Movie
    queryset = Movie.objects.filter(draft=False)
    template_name = "movies/movies.html"


class MovieDetailView(GenreYear, DetailView):
    """Полное описание фильма"""
    model = Movie
    slug_field = "url"  # поле по которому производится поиск
    template_name = "movies/movie_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['star_form'] = RatingForm()
        return context


class AddReview(View):
    """Отзыв"""

    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get('parent', None):
                form.parent_id = int(request.POST.get('parent'))
            form.movie = movie
            form.save()
        return redirect(movie.get_absolute_url())


class ActorView(GenreYear, DetailView):
    """Вывод информации об актере"""
    model = Actor
    template_name = 'movies/actor.html'
    slug_field = 'name'


class AddStarRating(View):
    """Добавление рейтнга фильму"""

    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        Rating.objects.update_or_create(
            ip=self.get_client_ip(request),
            stars=RatingStar.objects.get(value=int(request.POST.get('star'))),
            movie=Movie.objects.get(title=request.POST.get('movie'))
        )
        return HttpResponse(status=201)


class FilterMoviesView(GenreYear, ListView):
    """Фильтр фильмов"""
    template_name = "movies/movies.html"

    def get_queryset(self):
        queryset = Movie.objects.filter(Q(year__in=list(map(int, self.request.GET.getlist('year')))) |
                                        Q(genres__in=self.request.GET.getlist('genre')))
        return queryset


class Search(ListView):
    """Поиск фильмов"""

    paginate_by = 3
    template_name = "movies/movies.html"

    def get_queryset(self):
        return Movie.objects.filter(title__icontains=self.request.GET.get('q'))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['q'] = self.request.GET.get('q')
        return context

main/templates/movies/actor.html
{% extends 'base.html' %}
{% block title %}{{ actor.name }}{% endblock %}
{% block content %}

<div class="left-ads-display col-lg-8">
    <div class="row">
        <div class="desc1-left col-md-6">
            <img src="{{ actor.image.url }}" class="img-fluid">
        </div>
        <div class="desc1-right col-md-6 pl-lg-4">
            <h3 class="editContent">
                {{ actor.name }}
            </h3>
            <h5 class="editContent"></h5>
            <ul>
                <li><span><b>Возраст:</b> {{ actor.age }}</span></li>
                <li>
                    <span>
                        <b>Режиссер таких фильмов как:</b>
                        {% for movie in actor.film_director.all %}
                            {{ movie.title }}
                        {% endfor %}
                    </span>
                </li>
                <li>
                    <span>
                        <b>Актер в таких фильмах:</b>
                        {% for movie in actor.film_actor.all %}
                            {{ movie.title }}
                        {% endfor %}
                    </span>
                </li>
            </ul>
        </div>
    </div>
    <div class="row sub-para-w3layouts mt-5">
        <h3 class="shop-sing editContent">
            {{ actor.name }}
        </h3>
        <p class="editContent">{{ actor.description|safe }}</p>
    </div>
</div>
{% endblock content %}
                

main/templates/movies/movie_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="left-ads-display col-lg-8">
    <div class="row">
        <div class="desc1-left col-md-6">
            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
        </div>
        <div class="desc1-right col-md-6 pl-lg-4">
            <h3 class="editContent">
                {{ movie.title }}
            </h3>
            <h5 class="editContent"></h5>
            <ul>
                <li><span><b>Год:</b> {{ movie.year }}</span></li>
                <li><span><b>Страна:</b> {{ movie.country }}</span>
                </li>
                <li><span><b>Слоган:</b> {{ movie.tagline }}</span>
                </li>
                <li>
                    <span>
                        <b>Режиссер:</b>
                        {% for director in movie.directors.all %}
                            <a href="{{director.get_absolute_url}}">
                                {{ director.name }}
                            </a>
                        {% endfor %}
                    </span>
                </li>

                <li>
                    <span>
                        <b>Актеры:</b>
                        {% for actor in movie.actors.all %}
                                <a href="{{actor.get_absolute_url}}">
                                    {{ actor.name }}
                                </a>
                        {% endfor %}
                    </span>
                </li>
                <li><span><b>Жанр:</b>
                    {% for genre in movie.genres.all %}
                            {{ genre.name }}
                    {% endfor %}
                </span>
                </li>
                <li><span><b>Премьера в мире:</b> {{ movie.world_premiere }}</span>
                </li>
                <li>
                    <span><b>Бюджет:</b> ${{ movie.budget }}</span></li>
                <li>
                    <span><b>Сборы в США:</b> ${{ movie.fees_in_usa }}</span></li>
                <li><span><b>Сборы в мире:</b> ${{ movie.fees_in_world }}</span>
                </li>
                <li>
                    <form action="{% url 'add_rating' %}" method="post" name="rating">
                        <b>Рейтинг:</b>
                        {% csrf_token %}
                        <input type="hidden" name="movie" value="{{ movie.title }}">
                        <span class="rating">
                            {% for k,v in star_form.fields.stars.choices %}
                                <input type="submit" name="star" id="rating{{ v }}" value="{{ k }}">
                                <label for="rating{{ v }}"></label>
                            {% endfor %}
                        </span>
                        <span class="editContent"></span>
                    </form>
                </li>
                <div class="share-desc">
                    <div class="share">
                        <h4 class="editContent">
                            Share:</h4>
                        <ul class="w3layouts_social_list list-unstyled">
                            <li>
                                <a href="#" class="w3pvt_facebook editContent">
                                <span class="fa fa-facebook-f"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_twitter editContent">
                                <span class="fa fa-twitter"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_dribble editContent">
                                <span class="fa fa-dribbble"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </ul>
        </div>
    </div>
    <div class="row sub-para-w3layouts mt-5">

        <h3 class="shop-sing editContent">
            О фильме {{ movie.title }}</h3>
        <p>
            {% for img in movie.movieshots_set.all %}
                <img src="{{ img.image.url }}" class="img-fluid" style="max-width:350px;height:200px"
                    alt="{{ img.description }}">
            {% endfor %}
        </p>
        <p class="editContent">{{ movie.description|safe }}</p>
        <p class="mt-3 italic-blue editContent">
            <iframe width="560" height="315"
                    src="https://www.youtube.com/embed/A36LahZNUiE?controls=0"
                    frameborder="0" allow="accelerometer; autoplay;
                                                           encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen>

            </iframe>
        </p>
    </div>
    <hr>
    <div class="row" style="flex-flow:column">
        <div class="single-form-left">
            <div class="contact-single">
                <h3 class="editContent">
                    <span class="sub-tittle editContent">{{ movie.review_set.count }}</span>
                    Оставить отзыв
                </h3>
                <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4" id="formReview">
                    {% csrf_token %}
                    <input type="hidden" name="parent" id="contactparent" value="">
                    <div class="form-group editContent">
                        <label for="contactcomment" class="editContent">
                            Ваш комментарий
                        </label>
                        <textarea class="form-control border" rows="5" id="contactcomment" name="text"></textarea>
                    </div>
                    <div class="d-sm-flex">
                        <div class="col-sm-6 form-group p-0 editContent">
                            <label for="contactusername" class="editContent">
                                Имя
                            </label>
                            <input type="text" class="form-control border" id="contactusername" name="name">
                        </div>
                        <div class="col-sm-6 form-group ml-sm-3 editContent">
                            <label for="contactemail" class="editContent">
                                Email
                            </label>
                            <input type="email" class="form-control border" id="contactemail" name="email">
                        </div>
                    </div>
                    <button type="submit" class="mt-3 btn btn-success btn-block py-3">
                        Отправить
                    </button>
                </form>
            </div>
        </div>
        {% for review in movie.get_review %}
            <div class="media py-5">
                <img src="../../static/images/ava.jpg" class="mr-3 img-fluid" alt="image" style="width:50px;">
                <div class="media-body mt-4">
                    <h5 class="mt-0 editContent" >
                        {{ review.name }}
                    </h5>
                    <p class="mt-2 editContent">
                        {{ review.text }}
                    </p>
                    <a href="#formReview" onclick="addReview('{{ review.name }}','{{ review.id }}')">Ответить</a>
                    {% for rew in review.review_set.all %}
                        <div class="media mt-5 editContent">
                            <a class="pr-3" href="#">
                                <img src="../../static/images/ava.jpg" class="img-fluid "alt="image" style="width:50px;">
                            </a>
                            <div class="media-body">
                                <h5 class="mt-0 editContent">{{ rew.name }}</h5>
                                <p class="mt-2 editContent">
                                    {{ rew.text }}
                                </p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
</div>
<script type="text/javascript">
    function addReview(name, id){
        document.getElementById('contactparent').value = id;
        document.getElementById('contactcomment').value = name+',';
    }

    const rating = document.querySelector(selectors:'form[name=rating]');

    rating.addEventListener(type:'change', listener:function(e:Event){
        let data = new FormData(this)
        fetch( input: `${this.action}`, init:{
            method: 'POST',
            body: data
        }) Promise<Responce>
            .then(response => alert('Рейтинг Установлен')) Promise<void>
            .catch(error => alert('Ошибка'))

    });
</script>
{% endblock content %}
                

main/templates/movies/movies.html
{% extends 'base.html' %}

{% block content %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for movie in movie_list %}
                <div class="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4" >
                        <div class="men-thumb-item">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="" >
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ movie.get_absolute_url }}" class="editContent" >
                                    {{ movie.title }}
                                </a>
                            </h4>

                            <div class="product_price">
                                <div class="grid-price">
                                    <span class="money editContent" >
                                        {{ movie.tagline }}
                                    </span>
                                </div>
                            </div>
                            <ul class="stars">
                                <li><a href="#"><span class="fa fa-star" aria-hidden="true" ></span></a></li>
                                <li><a href="#"><span class="fa fa-star" aria-hidden="true" ></span></a></li>
                                <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true" ></span></a></li>
                                <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true" ></span></a></li>
                                <li><a href="#"><span class="fa fa-star-o" aria-hidden="true" ></span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}